### ISSUE TITLE
Add library for validation

### ISSUE THREAD

**Issue by krolow** [macarenajs/macarenajs#2]
Check how validation should happens

- if should add some entity / schema
- if should live to service validate as it goes

Some libraries to check:

- https://github.com/hapijs/joi

**Comment by moacirosa** [comment]
I was using `hapijs` and its ecosystem. [Joi](https://github.com/hapijs/joi) is really great and comfortable to use. You can make deep validations. I would say it deserves some time for evaluation.

**Comment by krolow** [comment]
yeah Joi is cool, i was wondering if they have had added support to async but it's seems they [did not yet](https://github.com/hapijs/joi/issues/1173)

I like their fluent interface I going to give a look if I can find some similar interface in other lib

**Comment by krolow** [comment]
I have found https://github.com/Atinux/schema-inspector#a_howTo

it does santization, validation and has async support

**Comment by krolow** [comment]
i tried use schema but in the end it was not looking nice...

endup using https://github.com/jquense/yup

quite similar interface of joi and ability to do async validations
